import YahooFantasyService from './yahoo-fantasy-service.mjs';
import nock from 'nock';

test('generate scout report for a given date', async () => {
  nock('https://fantasysports.yahooapis.com')
    .get('/fantasy/v2/users;use_login=1/teams/matchups;weeks=1/teams/roster')
    .reply(200, responseBodyXml);

  const fantasyService = new YahooFantasyService();
  const user = {
    token: 'something'
  };

  const expectedMatchup = {
    matchup: [{
      name: 'LA Kardashians',
      team_key: '402.l.23350.t.2',
      url: 'https://basketball.fantasysports.yahoo.com/nba/23350/2',
      roster: expect.arrayContaining([{
        player_key: '402.p.5161',
        name: 'CJ McCollum',
        selected_position: 'PG',
        team: 'POR'
      }])
    }, {
      name: 'Manglre',
      team_key: '402.l.23350.t.1',
      url: 'https://basketball.fantasysports.yahoo.com/nba/23350/1',
      roster: expect.arrayContaining([
        {
          player_key: '402.p.4895',
          name: 'Marcus Morris Sr.',
          selected_position: 'BN',
          team: 'LAC'
        },
        {
          player_key: '402.p.5464',
          name: 'Kristaps Porzingis',
          selected_position: 'IL',
          team: 'DAL'
        }
      ])
    }]
  };

  const matchup = await fantasyService.retrieveMatchup(user, 1);
  expect(matchup).toMatchObject(expectedMatchup);
});

const responseBodyXml =
  `<?xml version="1.0" encoding="UTF-8"?>
<fantasy_content xml:lang="en-US" yahoo:uri="http://fantasysports.yahooapis.com/fantasy/v2/users;use_login=1/teams/matchups;weeks=1/teams/roster" time="93.557834625244ms" copyright="Data provided by Yahoo! and STATS, LLC" refresh_rate="60" xmlns:yahoo="http://www.yahooapis.com/v1/base.rng" xmlns="http://fantasysports.yahooapis.com/fantasy/v2/base.rng">
 <users count="1">
  <user>
   <guid>23E4B7XXH4LBFOI2BKSWUQKCOQ</guid>
   <teams count="1">
    <team>
     <team_key>402.l.23350.t.2</team_key>
     <team_id>2</team_id>
     <name>LA Kardashians</name>
     <is_owned_by_current_login>1</is_owned_by_current_login>
     <url>https://basketball.fantasysports.yahoo.com/nba/23350/2</url>
     <team_logos>
      <team_logo>
       <size>large</size>
       <url>https://s.yimg.com/cv/apiv2/default/nba/nba_11_k.png</url>
      </team_logo>
     </team_logos>
     <waiver_priority>2</waiver_priority>
     <faab_balance>200</faab_balance>
     <number_of_moves>1</number_of_moves>
     <number_of_trades>0</number_of_trades>
     <roster_adds>
      <coverage_type>week</coverage_type>
      <coverage_value>1</coverage_value>
      <value>0</value>
     </roster_adds>
     <league_scoring_type>head</league_scoring_type>
     <has_draft_grade>0</has_draft_grade>
     <auction_budget_total>200</auction_budget_total>
     <auction_budget_spent>199</auction_budget_spent>
     <managers>
      <manager>
       <manager_id>2</manager_id>
       <nickname>Mandy</nickname>
       <guid>23E4B7XXH4LBFOI2BKSWUQKCOQ</guid>
       <is_current_login>1</is_current_login>
       <email>mundi.c@gmail.com</email>
       <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
      </manager>
     </managers>
     <matchups count="1">
      <matchup>
       <week>1</week>
       <week_start>2020-12-22</week_start>
       <week_end>2020-12-27</week_end>
       <status>midevent</status>
       <is_playoffs>0</is_playoffs>
       <is_consolation>0</is_consolation>
       <stat_winners>
        <stat_winner>
         <stat_id>5</stat_id>
         <winner_team_key>402.l.23350.t.1</winner_team_key>
        </stat_winner>
        <stat_winner>
         <stat_id>8</stat_id>
         <winner_team_key>402.l.23350.t.1</winner_team_key>
        </stat_winner>
        <stat_winner>
         <stat_id>10</stat_id>
         <winner_team_key>402.l.23350.t.1</winner_team_key>
        </stat_winner>
        <stat_winner>
         <stat_id>12</stat_id>
         <winner_team_key>402.l.23350.t.1</winner_team_key>
        </stat_winner>
        <stat_winner>
         <stat_id>15</stat_id>
         <winner_team_key>402.l.23350.t.1</winner_team_key>
        </stat_winner>
        <stat_winner>
         <stat_id>16</stat_id>
         <winner_team_key>402.l.23350.t.1</winner_team_key>
        </stat_winner>
        <stat_winner>
         <stat_id>17</stat_id>
         <winner_team_key>402.l.23350.t.1</winner_team_key>
        </stat_winner>
        <stat_winner>
         <stat_id>18</stat_id>
         <winner_team_key>402.l.23350.t.1</winner_team_key>
        </stat_winner>
        <stat_winner>
         <stat_id>19</stat_id>
         <winner_team_key>402.l.23350.t.1</winner_team_key>
        </stat_winner>
       </stat_winners>
       <teams count="2">
        <team>
         <team_key>402.l.23350.t.2</team_key>
         <team_id>2</team_id>
         <name>LA Kardashians</name>
         <is_owned_by_current_login>1</is_owned_by_current_login>
         <url>https://basketball.fantasysports.yahoo.com/nba/23350/2</url>
         <team_logos>
          <team_logo>
           <size>large</size>
           <url>https://s.yimg.com/cv/apiv2/default/nba/nba_11_k.png</url>
          </team_logo>
         </team_logos>
         <waiver_priority>2</waiver_priority>
         <faab_balance>200</faab_balance>
         <number_of_moves>1</number_of_moves>
         <number_of_trades>0</number_of_trades>
         <roster_adds>
          <coverage_type>week</coverage_type>
          <coverage_value>1</coverage_value>
          <value>0</value>
         </roster_adds>
         <league_scoring_type>head</league_scoring_type>
         <has_draft_grade>0</has_draft_grade>
         <auction_budget_total>200</auction_budget_total>
         <auction_budget_spent>199</auction_budget_spent>
         <managers>
          <manager>
           <manager_id>2</manager_id>
           <nickname>Mandy</nickname>
           <guid>23E4B7XXH4LBFOI2BKSWUQKCOQ</guid>
           <is_current_login>1</is_current_login>
           <email>mundi.c@gmail.com</email>
           <image_url>https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg</image_url>
          </manager>
         </managers>
         <team_stats>
          <coverage_type>week</coverage_type>
          <week>1</week>
          <stats>
           <stat>
            <stat_id>9004003</stat_id>
            <value>/</value>
           </stat>
           <stat>
            <stat_id>5</stat_id>
            <value/>
           </stat>
           <stat>
            <stat_id>9007006</stat_id>
            <value>/</value>
           </stat>
           <stat>
            <stat_id>8</stat_id>
            <value/>
           </stat>
           <stat>
            <stat_id>10</stat_id>
            <value/>
           </stat>
           <stat>
            <stat_id>12</stat_id>
            <value/>
           </stat>
           <stat>
            <stat_id>15</stat_id>
            <value/>
           </stat>
           <stat>
            <stat_id>16</stat_id>
            <value/>
           </stat>
           <stat>
            <stat_id>17</stat_id>
            <value/>
           </stat>
           <stat>
            <stat_id>18</stat_id>
            <value/>
           </stat>
           <stat>
            <stat_id>19</stat_id>
            <value/>
           </stat>
          </stats>
         </team_stats>
         <team_points>
          <coverage_type>week</coverage_type>
          <week>1</week>
          <total>0</total>
         </team_points>
         <team_remaining_games>
          <coverage_type>week</coverage_type>
          <week>1</week>
          <total>
           <remaining_games>31</remaining_games>
           <live_games>0</live_games>
           <completed_games>0</completed_games>
          </total>
         </team_remaining_games>
         <roster>
          <coverage_type>date</coverage_type>
          <date>2020-12-23</date>
          <is_editable>1</is_editable>
          <players count="15">
           <player>
            <player_key>402.p.5161</player_key>
            <player_id>5161</player_id>
            <name>
             <full>CJ McCollum</full>
             <first>CJ</first>
             <last>McCollum</last>
             <ascii_first>CJ</ascii_first>
             <ascii_last>McCollum</ascii_last>
            </name>
            <editorial_player_key>nba.p.5161</editorial_player_key>
            <editorial_team_key>nba.t.22</editorial_team_key>
            <editorial_team_full_name>Portland Trail Blazers</editorial_team_full_name>
            <editorial_team_abbr>Por</editorial_team_abbr>
            <uniform_number>3</uniform_number>
            <display_position>PG,SG</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/91r9PTPrnmo1LxtR9WjGUg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10092019/5161.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/91r9PTPrnmo1LxtR9WjGUg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10092019/5161.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PG</primary_position>
            <eligible_positions>
             <position>PG</position>
             <position>SG</position>
             <position>G</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608179828</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>PG</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.5637</player_key>
            <player_id>5637</player_id>
            <name>
             <full>Buddy Hield</full>
             <first>Buddy</first>
             <last>Hield</last>
             <ascii_first>Buddy</ascii_first>
             <ascii_last>Hield</ascii_last>
            </name>
            <editorial_player_key>nba.p.5637</editorial_player_key>
            <editorial_team_key>nba.t.23</editorial_team_key>
            <editorial_team_full_name>Sacramento Kings</editorial_team_full_name>
            <editorial_team_abbr>Sac</editorial_team_abbr>
            <uniform_number>24</uniform_number>
            <display_position>SG</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/IteOk8sKZQfACEMs5F_fPw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/5637.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/IteOk8sKZQfACEMs5F_fPw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/5637.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SG</primary_position>
            <eligible_positions>
             <position>SG</position>
             <position>G</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1607753893</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>SG</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.5009</player_key>
            <player_id>5009</player_id>
            <name>
             <full>Bradley Beal</full>
             <first>Bradley</first>
             <last>Beal</last>
             <ascii_first>Bradley</ascii_first>
             <ascii_last>Beal</ascii_last>
            </name>
            <editorial_player_key>nba.p.5009</editorial_player_key>
            <editorial_team_key>nba.t.27</editorial_team_key>
            <editorial_team_full_name>Washington Wizards</editorial_team_full_name>
            <editorial_team_abbr>Was</editorial_team_abbr>
            <uniform_number>3</uniform_number>
            <display_position>SG,SF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/bInnsHXRCcLkgEueCoOL7w--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/5009.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/bInnsHXRCcLkgEueCoOL7w--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/5009.png</image_url>
            <is_undroppable>1</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SG</primary_position>
            <eligible_positions>
             <position>SG</position>
             <position>G</position>
             <position>SF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608430923</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>G</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.5325</player_key>
            <player_id>5325</player_id>
            <name>
             <full>T.J. Warren</full>
             <first>T.J.</first>
             <last>Warren</last>
             <ascii_first>T.J.</ascii_first>
             <ascii_last>Warren</ascii_last>
            </name>
            <status>GTD</status>
            <status_full>Game Time Decision</status_full>
            <injury_note>Foot</injury_note>
            <editorial_player_key>nba.p.5325</editorial_player_key>
            <editorial_team_key>nba.t.11</editorial_team_key>
            <editorial_team_full_name>Indiana Pacers</editorial_team_full_name>
            <editorial_team_abbr>Ind</editorial_team_abbr>
            <uniform_number>1</uniform_number>
            <display_position>SF,PF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/lxa2hvcLAvFlpBtu1KwexA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/5325.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/lxa2hvcLAvFlpBtu1KwexA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/5325.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SF</primary_position>
            <eligible_positions>
             <position>SF</position>
             <position>PF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608567629</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>SF</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.6163</player_key>
            <player_id>6163</player_id>
            <name>
             <full>Zion Williamson</full>
             <first>Zion</first>
             <last>Williamson</last>
             <ascii_first>Zion</ascii_first>
             <ascii_last>Williamson</ascii_last>
            </name>
            <editorial_player_key>nba.p.6163</editorial_player_key>
            <editorial_team_key>nba.t.3</editorial_team_key>
            <editorial_team_full_name>New Orleans Pelicans</editorial_team_full_name>
            <editorial_team_abbr>NO</editorial_team_abbr>
            <uniform_number>1</uniform_number>
            <display_position>PF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/BqYJocgNJFO4S9l6Y2t5uA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10102019/6163.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/BqYJocgNJFO4S9l6Y2t5uA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10102019/6163.png</image_url>
            <is_undroppable>1</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PF</primary_position>
            <eligible_positions>
             <position>PF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608606466</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>PF</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.5352</player_key>
            <player_id>5352</player_id>
            <name>
             <full>Nikola Jokic</full>
             <first>Nikola</first>
             <last>Jokic</last>
             <ascii_first>Nikola</ascii_first>
             <ascii_last>Jokic</ascii_last>
            </name>
            <editorial_player_key>nba.p.5352</editorial_player_key>
            <editorial_team_key>nba.t.7</editorial_team_key>
            <editorial_team_full_name>Denver Nuggets</editorial_team_full_name>
            <editorial_team_abbr>Den</editorial_team_abbr>
            <uniform_number>15</uniform_number>
            <display_position>PF,C</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/s15n1kUDHnoAyRrngWhYxQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/5352.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/s15n1kUDHnoAyRrngWhYxQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/5352.png</image_url>
            <is_undroppable>1</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PF</primary_position>
            <eligible_positions>
             <position>PF</position>
             <position>F</position>
             <position>C</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1607831166</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>F</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.5832</player_key>
            <player_id>5832</player_id>
            <name>
             <full>John Collins</full>
             <first>John</first>
             <last>Collins</last>
             <ascii_first>John</ascii_first>
             <ascii_last>Collins</ascii_last>
            </name>
            <editorial_player_key>nba.p.5832</editorial_player_key>
            <editorial_team_key>nba.t.1</editorial_team_key>
            <editorial_team_full_name>Atlanta Hawks</editorial_team_full_name>
            <editorial_team_abbr>Atl</editorial_team_abbr>
            <uniform_number>20</uniform_number>
            <display_position>PF,C</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/Yw5pfzV2sNapasjXn7OAKQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/5832.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/Yw5pfzV2sNapasjXn7OAKQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/5832.png</image_url>
            <is_undroppable>1</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PF</primary_position>
            <eligible_positions>
             <position>PF</position>
             <position>F</position>
             <position>C</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608591496</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>C</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.5253</player_key>
            <player_id>5253</player_id>
            <name>
             <full>Robert Covington</full>
             <first>Robert</first>
             <last>Covington</last>
             <ascii_first>Robert</ascii_first>
             <ascii_last>Covington</ascii_last>
            </name>
            <editorial_player_key>nba.p.5253</editorial_player_key>
            <editorial_team_key>nba.t.22</editorial_team_key>
            <editorial_team_full_name>Portland Trail Blazers</editorial_team_full_name>
            <editorial_team_abbr>Por</editorial_team_abbr>
            <uniform_number>23</uniform_number>
            <display_position>PF,C</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/2eecWwG9oXE7jB7E8dyO5w--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12172020/5253.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/2eecWwG9oXE7jB7E8dyO5w--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12172020/5253.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PF</primary_position>
            <eligible_positions>
             <position>PF</position>
             <position>F</position>
             <position>C</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608179494</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>C</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.4764</player_key>
            <player_id>4764</player_id>
            <name>
             <full>Hassan Whiteside</full>
             <first>Hassan</first>
             <last>Whiteside</last>
             <ascii_first>Hassan</ascii_first>
             <ascii_last>Whiteside</ascii_last>
            </name>
            <editorial_player_key>nba.p.4764</editorial_player_key>
            <editorial_team_key>nba.t.23</editorial_team_key>
            <editorial_team_full_name>Sacramento Kings</editorial_team_full_name>
            <editorial_team_abbr>Sac</editorial_team_abbr>
            <uniform_number>20</uniform_number>
            <display_position>PF,C</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/ApNR3F_1Dg1XdUxMCFoR7w--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12172020/4764.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/ApNR3F_1Dg1XdUxMCFoR7w--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12172020/4764.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PF</primary_position>
            <eligible_positions>
             <position>PF</position>
             <position>F</position>
             <position>C</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608098934</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>Util</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.5764</player_key>
            <player_id>5764</player_id>
            <name>
             <full>Lonzo Ball</full>
             <first>Lonzo</first>
             <last>Ball</last>
             <ascii_first>Lonzo</ascii_first>
             <ascii_last>Ball</ascii_last>
            </name>
            <editorial_player_key>nba.p.5764</editorial_player_key>
            <editorial_team_key>nba.t.3</editorial_team_key>
            <editorial_team_full_name>New Orleans Pelicans</editorial_team_full_name>
            <editorial_team_abbr>NO</editorial_team_abbr>
            <uniform_number>2</uniform_number>
            <display_position>PG,SG</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/dCP7UUPvO8oa3_XHrO.w8g--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10102019/5764.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/dCP7UUPvO8oa3_XHrO.w8g--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10102019/5764.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PG</primary_position>
            <eligible_positions>
             <position>PG</position>
             <position>SG</position>
             <position>G</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608584304</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>Util</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.6175</player_key>
            <player_id>6175</player_id>
            <name>
             <full>Tyler Herro</full>
             <first>Tyler</first>
             <last>Herro</last>
             <ascii_first>Tyler</ascii_first>
             <ascii_last>Herro</ascii_last>
            </name>
            <editorial_player_key>nba.p.6175</editorial_player_key>
            <editorial_team_key>nba.t.14</editorial_team_key>
            <editorial_team_full_name>Miami Heat</editorial_team_full_name>
            <editorial_team_abbr>Mia</editorial_team_abbr>
            <uniform_number>14</uniform_number>
            <display_position>PG,SG,SF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/rkzl6G1_Ohe2y6ZtQD1djg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/6175.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/rkzl6G1_Ohe2y6ZtQD1djg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/6175.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PG</primary_position>
            <eligible_positions>
             <position>PG</position>
             <position>SG</position>
             <position>G</position>
             <position>SF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608328656</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>BN</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.4468</player_key>
            <player_id>4468</player_id>
            <name>
             <full>Danilo Gallinari</full>
             <first>Danilo</first>
             <last>Gallinari</last>
             <ascii_first>Danilo</ascii_first>
             <ascii_last>Gallinari</ascii_last>
            </name>
            <editorial_player_key>nba.p.4468</editorial_player_key>
            <editorial_team_key>nba.t.1</editorial_team_key>
            <editorial_team_full_name>Atlanta Hawks</editorial_team_full_name>
            <editorial_team_abbr>Atl</editorial_team_abbr>
            <uniform_number>8</uniform_number>
            <display_position>SF,PF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/eJf5xuq7qljHYQhoDiz5bQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/4468.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/eJf5xuq7qljHYQhoDiz5bQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/4468.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SF</primary_position>
            <eligible_positions>
             <position>SF</position>
             <position>PF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608262138</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>BN</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.4246</player_key>
            <player_id>4246</player_id>
            <name>
             <full>Mike Conley</full>
             <first>Mike</first>
             <last>Conley</last>
             <ascii_first>Mike</ascii_first>
             <ascii_last>Conley</ascii_last>
            </name>
            <editorial_player_key>nba.p.4246</editorial_player_key>
            <editorial_team_key>nba.t.26</editorial_team_key>
            <editorial_team_full_name>Utah Jazz</editorial_team_full_name>
            <editorial_team_abbr>Uta</editorial_team_abbr>
            <uniform_number>10</uniform_number>
            <display_position>PG</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/EUjNuYJac5QsroVvIzUKXg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/4246.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/EUjNuYJac5QsroVvIzUKXg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/4246.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PG</primary_position>
            <eligible_positions>
             <position>PG</position>
             <position>G</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608269764</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>BN</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.5194</player_key>
            <player_id>5194</player_id>
            <name>
             <full>Tim Hardaway Jr.</full>
             <first>Tim</first>
             <last>Hardaway Jr.</last>
             <ascii_first>Tim</ascii_first>
             <ascii_last>Hardaway Jr.</ascii_last>
            </name>
            <editorial_player_key>nba.p.5194</editorial_player_key>
            <editorial_team_key>nba.t.6</editorial_team_key>
            <editorial_team_full_name>Dallas Mavericks</editorial_team_full_name>
            <editorial_team_abbr>Dal</editorial_team_abbr>
            <uniform_number>11</uniform_number>
            <display_position>SG,SF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/C8rTkLIn0yFQFNc9ZjQMqQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/5194.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/C8rTkLIn0yFQFNc9ZjQMqQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/5194.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SG</primary_position>
            <eligible_positions>
             <position>SG</position>
             <position>G</position>
             <position>SF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608266114</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>BN</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
           <player>
            <player_key>402.p.4892</player_key>
            <player_id>4892</player_id>
            <name>
             <full>Klay Thompson</full>
             <first>Klay</first>
             <last>Thompson</last>
             <ascii_first>Klay</ascii_first>
             <ascii_last>Thompson</ascii_last>
            </name>
            <status>INJ</status>
            <status_full>Injured (IL-eligible)</status_full>
            <injury_note>Achilles</injury_note>
            <editorial_player_key>nba.p.4892</editorial_player_key>
            <editorial_team_key>nba.t.9</editorial_team_key>
            <editorial_team_full_name>Golden State Warriors</editorial_team_full_name>
            <editorial_team_abbr>GS</editorial_team_abbr>
            <uniform_number>11</uniform_number>
            <display_position>SG,SF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/mQOgdTagEa.g6en.tcBGpg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/4892.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/mQOgdTagEa.g6en.tcBGpg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/4892.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SG</primary_position>
            <eligible_positions>
             <position>SG</position>
             <position>G</position>
             <position>SF</position>
             <position>F</position>
             <position>Util</position>
             <position>IL</position>
            </eligible_positions>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>IL</position>
             <is_flex>0</is_flex>
            </selected_position>
            <is_editable>1</is_editable>
           </player>
          </players>
         </roster>
        </team>
        <team>
         <team_key>402.l.23350.t.1</team_key>
         <team_id>1</team_id>
         <name>Manglre</name>
         <url>https://basketball.fantasysports.yahoo.com/nba/23350/1</url>
         <team_logos>
          <team_logo>
           <size>large</size>
           <url>https://yahoofantasysports-res.cloudinary.com/image/upload/t_s192sq/fantasy-logos/37698860244_a07a46.jpg</url>
          </team_logo>
         </team_logos>
         <waiver_priority>10</waiver_priority>
         <faab_balance>200</faab_balance>
         <number_of_moves>1</number_of_moves>
         <number_of_trades>0</number_of_trades>
         <roster_adds>
          <coverage_type>week</coverage_type>
          <coverage_value>1</coverage_value>
          <value>0</value>
         </roster_adds>
         <league_scoring_type>head</league_scoring_type>
         <has_draft_grade>0</has_draft_grade>
         <auction_budget_total>200</auction_budget_total>
         <auction_budget_spent>200</auction_budget_spent>
         <managers>
          <manager>
           <manager_id>1</manager_id>
           <nickname>Will</nickname>
           <guid>5ULVA4HTGVFJ72DVSIIATXJIIY</guid>
           <is_commissioner>1</is_commissioner>
           <email>pennyish@yahoo.com</email>
           <image_url>https://s.yimg.com/ag/images/4522/38730940526_2f409f_64sq.jpg</image_url>
          </manager>
         </managers>
         <team_stats>
          <coverage_type>week</coverage_type>
          <week>1</week>
          <stats>
           <stat>
            <stat_id>9004003</stat_id>
            <value>21/35</value>
           </stat>
           <stat>
            <stat_id>5</stat_id>
            <value>.600</value>
           </stat>
           <stat>
            <stat_id>9007006</stat_id>
            <value>3/5</value>
           </stat>
           <stat>
            <stat_id>8</stat_id>
            <value>.600</value>
           </stat>
           <stat>
            <stat_id>10</stat_id>
            <value>9</value>
           </stat>
           <stat>
            <stat_id>12</stat_id>
            <value>54</value>
           </stat>
           <stat>
            <stat_id>15</stat_id>
            <value>15</value>
           </stat>
           <stat>
            <stat_id>16</stat_id>
            <value>8</value>
           </stat>
           <stat>
            <stat_id>17</stat_id>
            <value>1</value>
           </stat>
           <stat>
            <stat_id>18</stat_id>
            <value>1</value>
           </stat>
           <stat>
            <stat_id>19</stat_id>
            <value>8</value>
           </stat>
          </stats>
         </team_stats>
         <team_points>
          <coverage_type>week</coverage_type>
          <week>1</week>
          <total>9</total>
         </team_points>
         <team_remaining_games>
          <coverage_type>week</coverage_type>
          <week>1</week>
          <total>
           <remaining_games>31</remaining_games>
           <live_games>0</live_games>
           <completed_games>4</completed_games>
          </total>
         </team_remaining_games>
         <roster>
          <coverage_type>date</coverage_type>
          <date>2020-12-23</date>
          <is_editable>0</is_editable>
          <players count="15">
           <player>
            <player_key>402.p.5650</player_key>
            <player_id>5650</player_id>
            <name>
             <full>Malik Beasley</full>
             <first>Malik</first>
             <last>Beasley</last>
             <ascii_first>Malik</ascii_first>
             <ascii_last>Beasley</ascii_last>
            </name>
            <editorial_player_key>nba.p.5650</editorial_player_key>
            <editorial_team_key>nba.t.16</editorial_team_key>
            <editorial_team_full_name>Minnesota Timberwolves</editorial_team_full_name>
            <editorial_team_abbr>Min</editorial_team_abbr>
            <uniform_number>5</uniform_number>
            <display_position>PG,SG</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/8J3_cBXlcC9t5IS4R_o1FA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12172020/5650.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/8J3_cBXlcC9t5IS4R_o1FA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12172020/5650.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PG</primary_position>
            <eligible_positions>
             <position>PG</position>
             <position>SG</position>
             <position>G</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608587175</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>PG</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.6165</player_key>
            <player_id>6165</player_id>
            <name>
             <full>RJ Barrett</full>
             <first>RJ</first>
             <last>Barrett</last>
             <ascii_first>RJ</ascii_first>
             <ascii_last>Barrett</ascii_last>
            </name>
            <editorial_player_key>nba.p.6165</editorial_player_key>
            <editorial_team_key>nba.t.18</editorial_team_key>
            <editorial_team_full_name>New York Knicks</editorial_team_full_name>
            <editorial_team_abbr>NY</editorial_team_abbr>
            <uniform_number>9</uniform_number>
            <display_position>SG,SF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/tc.D3WC1jZr.nAtV2WGi3A--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/6165.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/tc.D3WC1jZr.nAtV2WGi3A--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/6165.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SG</primary_position>
            <eligible_positions>
             <position>SG</position>
             <position>G</position>
             <position>SF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608347335</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>SG</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.6164</player_key>
            <player_id>6164</player_id>
            <name>
             <full>Ja Morant</full>
             <first>Ja</first>
             <last>Morant</last>
             <ascii_first>Ja</ascii_first>
             <ascii_last>Morant</ascii_last>
            </name>
            <editorial_player_key>nba.p.6164</editorial_player_key>
            <editorial_team_key>nba.t.29</editorial_team_key>
            <editorial_team_full_name>Memphis Grizzlies</editorial_team_full_name>
            <editorial_team_abbr>Mem</editorial_team_abbr>
            <uniform_number>12</uniform_number>
            <display_position>PG</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/Y4gWm9gW_TOXJneSp2v87g--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/6164.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/Y4gWm9gW_TOXJneSp2v87g--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/6164.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PG</primary_position>
            <eligible_positions>
             <position>PG</position>
             <position>G</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608003572</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>G</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.5153</player_key>
            <player_id>5153</player_id>
            <name>
             <full>Victor Oladipo</full>
             <first>Victor</first>
             <last>Oladipo</last>
             <ascii_first>Victor</ascii_first>
             <ascii_last>Oladipo</ascii_last>
            </name>
            <editorial_player_key>nba.p.5153</editorial_player_key>
            <editorial_team_key>nba.t.11</editorial_team_key>
            <editorial_team_full_name>Indiana Pacers</editorial_team_full_name>
            <editorial_team_abbr>Ind</editorial_team_abbr>
            <uniform_number>4</uniform_number>
            <display_position>SG,SF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/hzFIG5Kl.GMlSBHK5ylRDw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/5153.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/hzFIG5Kl.GMlSBHK5ylRDw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/5153.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SG</primary_position>
            <eligible_positions>
             <position>SG</position>
             <position>G</position>
             <position>SF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608343156</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>SF</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.4913</player_key>
            <player_id>4913</player_id>
            <name>
             <full>Bojan Bogdanovic</full>
             <first>Bojan</first>
             <last>Bogdanovic</last>
             <ascii_first>Bojan</ascii_first>
             <ascii_last>Bogdanovic</ascii_last>
            </name>
            <editorial_player_key>nba.p.4913</editorial_player_key>
            <editorial_team_key>nba.t.26</editorial_team_key>
            <editorial_team_full_name>Utah Jazz</editorial_team_full_name>
            <editorial_team_abbr>Uta</editorial_team_abbr>
            <uniform_number>44</uniform_number>
            <display_position>SF,PF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/5xBq1LFwBLv6ThugJEuwnw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/4913.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/5xBq1LFwBLv6ThugJEuwnw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/4913.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SF</primary_position>
            <eligible_positions>
             <position>SF</position>
             <position>PF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1607834238</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>PF</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.5500</player_key>
            <player_id>5500</player_id>
            <name>
             <full>Josh Richardson</full>
             <first>Josh</first>
             <last>Richardson</last>
             <ascii_first>Josh</ascii_first>
             <ascii_last>Richardson</ascii_last>
            </name>
            <editorial_player_key>nba.p.5500</editorial_player_key>
            <editorial_team_key>nba.t.6</editorial_team_key>
            <editorial_team_full_name>Dallas Mavericks</editorial_team_full_name>
            <editorial_team_abbr>Dal</editorial_team_abbr>
            <uniform_number>0</uniform_number>
            <display_position>SG,SF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/NsjVebDTtF.uzmDWgcxUuw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12152020/5500.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/NsjVebDTtF.uzmDWgcxUuw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12152020/5500.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SG</primary_position>
            <eligible_positions>
             <position>SG</position>
             <position>G</position>
             <position>SF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608586657</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>F</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.5827</player_key>
            <player_id>5827</player_id>
            <name>
             <full>Bam Adebayo</full>
             <first>Bam</first>
             <last>Adebayo</last>
             <ascii_first>Bam</ascii_first>
             <ascii_last>Adebayo</ascii_last>
            </name>
            <editorial_player_key>nba.p.5827</editorial_player_key>
            <editorial_team_key>nba.t.14</editorial_team_key>
            <editorial_team_full_name>Miami Heat</editorial_team_full_name>
            <editorial_team_abbr>Mia</editorial_team_abbr>
            <uniform_number>13</uniform_number>
            <display_position>PF,C</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/EXf6nJ5P7Yd887XrJrkucQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/5827.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/EXf6nJ5P7Yd887XrJrkucQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/5827.png</image_url>
            <is_undroppable>1</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PF</primary_position>
            <eligible_positions>
             <position>PF</position>
             <position>F</position>
             <position>C</position>
             <position>Util</position>
            </eligible_positions>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>C</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.6232</player_key>
            <player_id>6232</player_id>
            <name>
             <full>Bol Bol</full>
             <first>Bol</first>
             <last>Bol</last>
             <ascii_first>Bol</ascii_first>
             <ascii_last>Bol</ascii_last>
            </name>
            <editorial_player_key>nba.p.6232</editorial_player_key>
            <editorial_team_key>nba.t.7</editorial_team_key>
            <editorial_team_full_name>Denver Nuggets</editorial_team_full_name>
            <editorial_team_abbr>Den</editorial_team_abbr>
            <uniform_number>10</uniform_number>
            <display_position>PF,C</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/JZyL8gtTfiQjc0qMG1YP1Q--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/6232.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/JZyL8gtTfiQjc0qMG1YP1Q--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/6232.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PF</primary_position>
            <eligible_positions>
             <position>PF</position>
             <position>F</position>
             <position>C</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608180563</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>C</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.5660</player_key>
            <player_id>5660</player_id>
            <name>
             <full>Dejounte Murray</full>
             <first>Dejounte</first>
             <last>Murray</last>
             <ascii_first>Dejounte</ascii_first>
             <ascii_last>Murray</ascii_last>
            </name>
            <editorial_player_key>nba.p.5660</editorial_player_key>
            <editorial_team_key>nba.t.24</editorial_team_key>
            <editorial_team_full_name>San Antonio Spurs</editorial_team_full_name>
            <editorial_team_abbr>SA</editorial_team_abbr>
            <uniform_number>5</uniform_number>
            <display_position>PG,SG</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/lwMlZUSwYndTDO_JI01TBA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/5660.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/lwMlZUSwYndTDO_JI01TBA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/5660.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PG</primary_position>
            <eligible_positions>
             <position>PG</position>
             <position>SG</position>
             <position>G</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608261771</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>Util</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.6016</player_key>
            <player_id>6016</player_id>
            <name>
             <full>Trae Young</full>
             <first>Trae</first>
             <last>Young</last>
             <ascii_first>Trae</ascii_first>
             <ascii_last>Young</ascii_last>
            </name>
            <editorial_player_key>nba.p.6016</editorial_player_key>
            <editorial_team_key>nba.t.1</editorial_team_key>
            <editorial_team_full_name>Atlanta Hawks</editorial_team_full_name>
            <editorial_team_abbr>Atl</editorial_team_abbr>
            <uniform_number>11</uniform_number>
            <display_position>PG</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/hpiIWmo.iTlSGmGcALE4GQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/6016.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/hpiIWmo.iTlSGmGcALE4GQ--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10142019/6016.png</image_url>
            <is_undroppable>1</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PG</primary_position>
            <eligible_positions>
             <position>PG</position>
             <position>G</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608435354</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>Util</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.3971</player_key>
            <player_id>3971</player_id>
            <name>
             <full>Lou Williams</full>
             <first>Lou</first>
             <last>Williams</last>
             <ascii_first>Lou</ascii_first>
             <ascii_last>Williams</ascii_last>
            </name>
            <editorial_player_key>nba.p.3971</editorial_player_key>
            <editorial_team_key>nba.t.12</editorial_team_key>
            <editorial_team_full_name>Los Angeles Clippers</editorial_team_full_name>
            <editorial_team_abbr>LAC</editorial_team_abbr>
            <uniform_number>23</uniform_number>
            <display_position>PG,SG</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/DF4r0zoUDIpQngNZHIp.8A--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10092019/3971.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/DF4r0zoUDIpQngNZHIp.8A--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10092019/3971.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PG</primary_position>
            <eligible_positions>
             <position>PG</position>
             <position>SG</position>
             <position>G</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1607920844</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>BN</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.5344</player_key>
            <player_id>5344</player_id>
            <name>
             <full>Joe Harris</full>
             <first>Joe</first>
             <last>Harris</last>
             <ascii_first>Joe</ascii_first>
             <ascii_last>Harris</ascii_last>
            </name>
            <editorial_player_key>nba.p.5344</editorial_player_key>
            <editorial_team_key>nba.t.17</editorial_team_key>
            <editorial_team_full_name>Brooklyn Nets</editorial_team_full_name>
            <editorial_team_abbr>Bkn</editorial_team_abbr>
            <uniform_number>12</uniform_number>
            <display_position>SG,SF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/858LBdmaOgXOyc_tvtRsSg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/5344.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/858LBdmaOgXOyc_tvtRsSg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10112019/5344.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SG</primary_position>
            <eligible_positions>
             <position>SG</position>
             <position>G</position>
             <position>SF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <has_recent_player_notes>1</has_recent_player_notes>
            <player_notes_last_timestamp>1608692740</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>BN</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.4725</player_key>
            <player_id>4725</player_id>
            <name>
             <full>Paul George</full>
             <first>Paul</first>
             <last>George</last>
             <ascii_first>Paul</ascii_first>
             <ascii_last>George</ascii_last>
            </name>
            <editorial_player_key>nba.p.4725</editorial_player_key>
            <editorial_team_key>nba.t.12</editorial_team_key>
            <editorial_team_full_name>Los Angeles Clippers</editorial_team_full_name>
            <editorial_team_abbr>LAC</editorial_team_abbr>
            <uniform_number>13</uniform_number>
            <display_position>SF,PF</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/S.6UbtlDrCi7l_lAyAJKkA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/4725.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/S.6UbtlDrCi7l_lAyAJKkA--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10082019/4725.png</image_url>
            <is_undroppable>1</is_undroppable>
            <position_type>P</position_type>
            <primary_position>SF</primary_position>
            <eligible_positions>
             <position>SF</position>
             <position>PF</position>
             <position>F</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <has_recent_player_notes>1</has_recent_player_notes>
            <player_notes_last_timestamp>1608703791</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>BN</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.4895</player_key>
            <player_id>4895</player_id>
            <name>
             <full>Marcus Morris Sr.</full>
             <first>Marcus</first>
             <last>Morris Sr.</last>
             <ascii_first>Marcus</ascii_first>
             <ascii_last>Morris Sr.</ascii_last>
            </name>
            <status>O</status>
            <status_full>Out (short-term injury)</status_full>
            <injury_note>Knee</injury_note>
            <editorial_player_key>nba.p.4895</editorial_player_key>
            <editorial_team_key>nba.t.12</editorial_team_key>
            <editorial_team_full_name>Los Angeles Clippers</editorial_team_full_name>
            <editorial_team_abbr>LAC</editorial_team_abbr>
            <uniform_number>31</uniform_number>
            <display_position>PF,C</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/YznI2AjBmNclarfi6bXAcg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12152020/4895.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/YznI2AjBmNclarfi6bXAcg--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/12152020/4895.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PF</primary_position>
            <eligible_positions>
             <position>PF</position>
             <position>F</position>
             <position>C</position>
             <position>Util</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608599565</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>BN</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
           <player>
            <player_key>402.p.5464</player_key>
            <player_id>5464</player_id>
            <name>
             <full>Kristaps Porzingis</full>
             <first>Kristaps</first>
             <last>Porzingis</last>
             <ascii_first>Kristaps</ascii_first>
             <ascii_last>Porzingis</ascii_last>
            </name>
            <status>INJ</status>
            <status_full>Injured (IL-eligible)</status_full>
            <injury_note>Knee</injury_note>
            <editorial_player_key>nba.p.5464</editorial_player_key>
            <editorial_team_key>nba.t.6</editorial_team_key>
            <editorial_team_full_name>Dallas Mavericks</editorial_team_full_name>
            <editorial_team_abbr>Dal</editorial_team_abbr>
            <uniform_number>6</uniform_number>
            <display_position>PF,C</display_position>
            <headshot>
             <url>https://s.yimg.com/iu/api/res/1.2/iAknnSQmGJqCjT2EdI5ARw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10102019/5464.png</url>
             <size>small</size>
            </headshot>
            <image_url>https://s.yimg.com/iu/api/res/1.2/iAknnSQmGJqCjT2EdI5ARw--~C/YXBwaWQ9eXNwb3J0cztjaD0yMzM2O2NyPTE7Y3c9MTc5MDtkeD04NTc7ZHk9MDtmaT11bGNyb3A7aD02MDtxPTEwMDt3PTQ2/https://s.yimg.com/xe/i/us/sp/v/nba_cutout/players_l/10102019/5464.png</image_url>
            <is_undroppable>0</is_undroppable>
            <position_type>P</position_type>
            <primary_position>PF</primary_position>
            <eligible_positions>
             <position>PF</position>
             <position>F</position>
             <position>C</position>
             <position>Util</position>
             <position>IL</position>
            </eligible_positions>
            <has_player_notes>1</has_player_notes>
            <player_notes_last_timestamp>1608324158</player_notes_last_timestamp>
            <selected_position>
             <coverage_type>date</coverage_type>
             <date>2020-12-23</date>
             <position>IL</position>
             <is_flex>0</is_flex>
            </selected_position>
           </player>
          </players>
         </roster>
        </team>
       </teams>
      </matchup>
     </matchups>
    </team>
   </teams>
  </user>
 </users>
</fantasy_content>
<!-- fantasy-sports-api- -public-production-bf1-5984fbf5f6-xgxhv Wed Dec 23 15:17:16 UTC 2020 -->
`;
